# THIS IS A GENERATED FILE
# Generated by: scrapy /home/smorblin/shopgrok-env/bin/testmaster update olympus --new  # noqa: E501
# Request URL: http://olympus.realpython.org/profiles  # noqa: E501
import os
import unittest
from scrapy_testmaster.utils import generate_test


class TestMaster(unittest.TestCase):
    def test__olympus__parse_login(self):
        files = os.listdir(
            os.path.dirname(
                os.path.abspath(__file__)
            )
        )
        files = [f for f in files if f.endswith('.bin')]
        self.maxDiff = None
        for f in files:
            file_path = os.path.join(os.path.dirname(__file__), f)
            print("Testing fixture '%s'" % (f))
            test = generate_test(os.path.abspath(file_path))
            test(self)


if __name__ == '__main__':
    unittest.main()
